"""changed measurement table

Revision ID: 7d8d71f3cd7b
Revises: 6ab6bba59dbf
Create Date: 2025-03-10 16:30:13.194038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8d71f3cd7b'
down_revision: Union[str, None] = '6ab6bba59dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('measurements', sa.Column('temp_sensor', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('temp_api', sa.Float(), nullable=True))
    op.drop_column('measurements', 'temp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('temp', sa.FLOAT(), nullable=True))
    op.drop_column('measurements', 'temp_api')
    op.drop_column('measurements', 'temp_sensor')
    op.drop_column('measurements', 'date')
    # ### end Alembic commands ###
